name: Slack notification
description: Post job conclusions of a workflow to Slack

inputs:
  slack-webhook:
    description: Slack webhook for the desired channel
    required: true
  repo:
    description: The owner and repository name where the workflow runs
    required: true
  run-id:
    description: ID of the workflow run to notify about
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
